# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    php_errors:
        log: true

when@test:
    framework:
        test: true
